Gabra wald k ae011
BetaMasaheft/Persons pull request #219
Opened 2020-09-14 19:45 UTC by DenisNosnitsin1970

new

2020-09-14 19:57 UTC, DenisNosnitsin1970 commented
Sorry, one Gabra Wald (45) is redundant. It is a result of the confusion I got after a computer problem on Saturday. I thought I lost Gabra Wald 44 and created 45, but 44 popped up. I will delete Gabra Wald 45.

2020-09-15 08:21 UTC, thea-m requested changes

2020-09-15 08:21 UTC, thea-m commented on new/PRS13144GabraWald.xml
> +                    <relation name="saws:isRelatedTo" active="PRS13144GabraWald" passive="PRS9451Tewoflos"/>
This saws relation should only be used between two works, not for persons. What is their exact relationship?

2020-09-15 12:53 UTC, merged

2020-09-16 12:07 UTC, thea-m commented
Could you delete PRS13145GabraWald now in a new branch (before we forget...)?