Opersons in BDLaethb4
BetaMasaheft/Persons pull request #240
Opened 2020-10-14 15:16 UTC by SusanneHummel

2020-10-14 15:23 UTC, MassimoVilla requested changes
Thanks!

2020-10-14 15:23 UTC, MassimoVilla commented on new/PRS13193Giyorgis.xml
> +                        passive="PRS13195PRS13194AmataSell"/>
ID to be fixed

2020-10-14 15:26 UTC, SusanneHummel commented on new/PRS13193Giyorgis.xml
> +                        passive="PRS13195PRS13194AmataSell"/>
Thank you! too many numbers today ....

2020-10-14 15:29 UTC, MassimoVilla approved these changes

2020-10-14 15:30 UTC, merged

2020-10-15 09:07 UTC, thea-m commented
(@SusanneHummel : There really is a second Gadla Giyorgis: https://betamasaheft.eu/persons/PRS13128GadlaGiyorgis/main)