Prs13205 yohannes
BetaMasaheft/Persons pull request #244
Opened 2020-10-20 18:01 UTC by MarcinKrawczuk

2020-10-23 12:41 UTC, DariaElagina commented on new/PRS13205Yohannes.xml
> +                    <occupation type="ecclesiastic">"bishop of Ethiopia"</occupation>
the quotation marks are not needed

2020-10-26 16:38 UTC, thea-m requested changes
Thank you!

2020-10-26 16:38 UTC, thea-m commented on new/PRS13205Yohannes.xml
> +                    <death/>
They are not wrong, but it is better to delete these empty elements to have a cleaner file.

2020-10-26 16:38 UTC, thea-m commented on new/PRS13205Yohannes.xml
> +                    <floruit>He is an author of a homily on Mary, in which
"the author"?

2020-10-27 08:30 UTC, thea-m approved these changes

2020-10-27 08:30 UTC, merged