corrected names
BetaMasaheft/Persons pull request #311
Opened 2020-12-17 11:22 UTC by thea-m

no other changes

2020-12-17 12:01 UTC, eu-genia requested changes

2020-12-17 12:01 UTC, eu-genia commented on PRS12001-13000/PRS12692VladimirBeneshevich.xml
> +                    <persName xml:lang="en" xml:id="n1">Vladimir Nikolaevič Beneshevič</persName>
```
<persName xml:lang="ru" xml:id="n1"><forename>Владимир Николаевич</forename> <surname>Бенешевич</surname></persName>
<persName xml:lang="ru" type="normalized" corresp="#n1"><forename>Vladimir Nikolaevič</forename> <surname>Beneshevič</surname></persName>
```

2020-12-17 12:01 UTC, eu-genia commented on new/PRS13241Archelaus.xml
>                  <person sameAs="Q244345" sex="1">
wd:Q244345

2021-01-05 10:46 UTC, thea-m commented
Thank you! I really think that for obvious corrections like this it is faster for the reviewer to carry them out directly in the files :)

2021-01-06 23:07 UTC, eu-genia approved these changes

2021-01-06 23:07 UTC, merged