Prs5585 isaiaht corr mk
BetaMasaheft/Persons pull request #377
Opened 2021-06-18 18:25 UTC by MarcinKrawczuk

It doesn't display correctly in the app,  I think it might be because /t/ was used instead of /n/ in <persName>, added a few things along the way.

2021-06-30 10:33 UTC, thea-m requested changes
Thank you! (If no one is assigned, no one receives an email and feels responsible, but still, sorry that this nice PR was lost!)

2021-06-30 10:33 UTC, thea-m commented on PRS5001-6000/PRS5585Isaiaht.xml
> +               <persName xml:lang="en" xml:id="n2">Isaiah of Schetis</persName>
I would propose the more common Scetis

2021-06-30 15:48 UTC, MarcinKrawczuk commented on PRS5001-6000/PRS5585Isaiaht.xml
> +               <persName xml:lang="en" xml:id="n2">Isaiah of Schetis</persName>
Sure

2021-07-01 08:36 UTC, thea-m approved these changes

2021-07-01 08:37 UTC, merged