Sisay
BetaMasaheft/Persons pull request #380
Opened 2021-06-23 10:13 UTC by Mahyewi

first pull request for the changes made on transcription and persons names

2021-06-23 10:20 UTC, PietroLiuzzo requested changes

2021-06-23 10:20 UTC, PietroLiuzzo commented on PRS1001-2000/PRS1012Abalez.xml
>                 <persName>
please add here also `@xml:id` and `@xml:lang`. also in other files you edited as necessary

2021-06-23 10:20 UTC, PietroLiuzzo commented on PRS1001-2000/PRS1015Abarra.xml
>                 <persName>
please remove the outer persName.
you should have person, and inside person a series of persNames

2021-06-23 10:20 UTC, PietroLiuzzo commented on PRS1001-2000/PRS1016AbarraG.xml
> -                   ʾAbarrā Gǝzāw
same as above.

2021-06-23 10:20 UTC, PietroLiuzzo commented on PRS1001-2000/PRS1016AbarraG.xml
>                 <persName type="alt">ʾAbbā Sǝbbār</persName>
perhaps this can also be written in gez, assigned an xml:id an a corresp

2021-06-23 10:20 UTC, PietroLiuzzo commented on PRS1001-2000/PRS1017AbarraK.xml
>                 <persName>
as above

2021-06-23 10:20 UTC, PietroLiuzzo commented on PRS1001-2000/PRS1018AbarraK.xml
> +         <change who="SS" when="2021-06-23">updated names</change>
please add this element with your initials to all the files

2021-06-23 10:20 UTC, PietroLiuzzo commented on PRS1001-2000/PRS1019AbarraT.xml
> +               <occupation> daǧǧ</occupation>
please add `@type`

2021-06-23 10:20 UTC, PietroLiuzzo commented on PRS1001-2000/PRS1020AbarraT.xml
> -
as above

2021-06-24 10:43 UTC, PietroLiuzzo commented
@Mahyewi please switch back to this branch, make the requested changes and commit to this branch, so we can merge it.

2022-09-27 10:52 UTC, thea-m approved these changes

2022-09-27 10:52 UTC, merged