Create PRS13437WalattaBM.xml
BetaMasaheft/Persons pull request #382
Opened 2021-06-23 15:01 UTC by thea-m

2021-06-23 16:48 UTC, DenisNosnitsin1970 requested changes

2021-06-23 16:48 UTC, DenisNosnitsin1970 commented on new/PRS13437WalattaBM.xml
> +                <title>Walatta Beta Maqdas</title>
Very unusual name. Sure that it is a personal (baptismal) name?

2021-06-28 07:44 UTC, thea-m commented
No, your intuition is absolutely right. I missread: it's actually ውስተ፡ ቤተ፡ መቅደስ, probably referring to the text. I'll merge this PR and then make a new one for the deletion of the record.

2021-06-28 07:45 UTC, merged

2025-03-03 09:38 UTC, eu-genia commented
@thea-m this record was deleted but it is still pointed to from RDW004, can you please check? thank you