new records
BetaMasaheft/Persons pull request #436
Opened 2021-09-01 15:41 UTC by thea-m

I'm back! 😄

2021-09-02 15:28 UTC, MassimoVilla requested changes
Thank you Thea! :)

2021-09-02 15:28 UTC, MassimoVilla commented on new/PRS13549SardaD.xml
> +                <title>Sarḍa Dǝngǝl</title>
Śarḍa

2021-09-02 15:28 UTC, MassimoVilla commented on new/PRS13549SardaD.xml
> +                    <persName xml:lang="gez" corresp="#n1" type="normalized">Sarḍa Dǝngǝl</persName>
Śarḍa

2021-09-07 14:42 UTC, thea-m commented
Thank you!

2021-10-06 09:47 UTC, thea-m commented
Can this be merged?

2021-10-06 10:41 UTC, MassimoVilla approved these changes

2021-10-06 10:41 UTC, merged