deleted PRS8423Salomon
BetaMasaheft/Persons pull request #456
Opened 2021-11-10 11:17 UTC by thea-m

https://github.com/BetaMasaheft/Documentation/issues/1831

2021-11-10 11:44 UTC, DenisNosnitsin1970 approved these changes

2021-11-10 12:03 UTC, eu-genia requested changes

2021-11-10 12:03 UTC, eu-genia commented on PRS8001-9000/PRS8422Salomon.xml
>                    <persName xml:lang="gez" corresp="#n1" type="normalized">Salomon II</persName>
I wonder if "II" should be marked up as addName
even `<addName>II</addName> (or <addName>III</addName>)`

2021-11-10 12:04 UTC, eu-genia commented on PRS8001-9000/PRS8422Salomon.xml
>                    <persName xml:lang="gez" xml:id="n1" type="birth">ሰሎሞን፡</persName>
Salomon is the regnal name

2021-11-10 12:04 UTC, eu-genia requested changes

2021-11-10 12:04 UTC, eu-genia commented on PRS8001-9000/PRS8422Salomon.xml
>                    <persName xml:lang="gez" xml:id="n2" type="birth">ገብረ፡ መድሕን፡</persName>
here type="birth" is correct

2021-11-18 12:28 UTC, thea-m commented on PRS8001-9000/PRS8422Salomon.xml
> +            <person sameAs="wd:Q717219" sex="1">
now I'm completely confused :D
I was working under the assumption PRS8422Salomon=Salomon II, 1796-1799=Q717219 (Salomon III in wikipedia)
and PRS8421Salomon=Salomon I, 1777-1779=Q343719 (Salomon II in wikipedia)

2021-11-18 13:22 UTC, eu-genia approved these changes

2021-11-18 13:22 UTC, merged