Prs13881 irenaeus
BetaMasaheft/Persons pull request #624
Opened 2022-08-29 19:16 UTC by MarcinKrawczuk

2022-08-30 09:37 UTC, thea-m requested changes
Thanks a lot!

2022-08-30 09:37 UTC, thea-m commented on new/PRS13881Irenaeus.xml
> +                    <persName xml:lang="gez" type="normalized" corresp="#n2">Herenewos ṗāṗṗās za-Sorǝm</persName>
same ṗāṗās question as in the work

2022-08-30 17:52 UTC, MarcinKrawczuk commented
Done!

wt., 30 sie 2022 o 11:38 thea-m ***@***.***> napisał(a):

> ***@***.**** requested changes on this pull request.
>
> Thanks a lot!
> ------------------------------
>
> In new/PRS13881Irenaeus.xml
> <https://github.com/BetaMasaheft/Persons/pull/624#discussion_r958249890>:
>
> > +              <keywords>
>
> +                <term key="martyr"></term>
>
> +              </keywords>
>
> +            </textClass>
>
> +        </profileDesc>
>
> +        <revisionDesc>
>
> +            <change who="MKr" when="2022-08-28">Created entity</change>
>
> +        </revisionDesc>
>
> +    </teiHeader>
>
> +    <text>
>
> +        <body>
>
> +            <listPerson>
>
> +                <person sameAs="Q240598" sex="1">
>
> +                    <persName xml:lang="en" xml:id="n1">Irenaeus of Sirmium</persName>
>
> +                    <persName xml:lang="gez" xml:id="n2">ሄሬኔዎስ፡ ጳጳስ፡ ዘሶርም፡</persName>
>
> +                    <persName xml:lang="gez" type="normalized" corresp="#n2">Herenewos ṗāṗṗās za-Sorǝm</persName>
>
>
> same ṗāṗās question as in the work
> ------------------------------
>
> In new/PRS13881Irenaeus.xml
> <https://github.com/BetaMasaheft/Persons/pull/624#discussion_r958251369>:
>
> > +            <change who="MKr" when="2022-08-28">Created entity</change>
>
> +        </revisionDesc>
>
> +    </teiHeader>
>
> +    <text>
>
> +        <body>
>
> +            <listPerson>
>
> +                <person sameAs="Q240598" sex="1">
>
> +                    <persName xml:lang="en" xml:id="n1">Irenaeus of Sirmium</persName>
>
> +                    <persName xml:lang="gez" xml:id="n2">ሄሬኔዎስ፡ ጳጳስ፡ ዘሶርም፡</persName>
>
> +                    <persName xml:lang="gez" type="normalized" corresp="#n2">Herenewos ṗāṗṗās za-Sorǝm</persName>
>
> +                    <faith type="Christianity"/>
>
> +                    <occupation type="ecclesiastic"/>
>
> +                    <birth/>
>
> +                    <death>304</death>
>
> +                    <floruit>Bishop of Sirmium in Pannonia (present-day Serbia), martyred during the Diocletianic persecution.</floruit>
>
> +                    <note>Commemorated on <date type="diesNatalis" ref="ethiocal:Nahase29">29 Naḥāse</date></note>
>
>
> A personal pet peeve, maybe a bit pedantic :) Sometimes, the commemoration
> in the Gadla samatat and the Synaxarion is not on the same day, so I think
> it would be good if we included in this sentence the source from which we
> took the date
> ------------------------------
>
> In new/PRS13881Irenaeus.xml
> <https://github.com/BetaMasaheft/Persons/pull/624#discussion_r958251372>:
>
> > +            <change who="MKr" when="2022-08-28">Created entity</change>
>
> +        </revisionDesc>
>
> +    </teiHeader>
>
> +    <text>
>
> +        <body>
>
> +            <listPerson>
>
> +                <person sameAs="Q240598" sex="1">
>
> +                    <persName xml:lang="en" xml:id="n1">Irenaeus of Sirmium</persName>
>
> +                    <persName xml:lang="gez" xml:id="n2">ሄሬኔዎስ፡ ጳጳስ፡ ዘሶርም፡</persName>
>
> +                    <persName xml:lang="gez" type="normalized" corresp="#n2">Herenewos ṗāṗṗās za-Sorǝm</persName>
>
> +                    <faith type="Christianity"/>
>
> +                    <occupation type="ecclesiastic"/>
>
> +                    <birth/>
>
> +                    <death>304</death>
>
> +                    <floruit>Bishop of Sirmium in Pannonia (present-day Serbia), martyred during the Diocletianic persecution.</floruit>
>
> +                    <note>Commemorated on <date type="diesNatalis" ref="ethiocal:Nahase29">29 Naḥāse</date></note>
>
>
> A personal pet peeve, maybe a bit pedantic :) Sometimes, the commemoration
> in the Gadla samatat and the Synaxarion is not on the same day, so I think
> it would be good if we included in this sentence the source from which we
> took the date
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Persons/pull/624#pullrequestreview-1089983520>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJSN6VZHGULGIWUNWO3V3XI75ANCNFSM5765A7SA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-31 09:01 UTC, thea-m approved these changes
Thanks!

2022-08-31 09:01 UTC, merged