Create PRS13975BadaMaryam.xml
BetaMasaheft/Persons pull request #675
Opened 2023-02-01 16:18 UTC by CarstenHoffmannMarburg

Created new Person ID for ቂሰ፡ ገበዝ፡ ባዕደ፡ ማርያም፡ - ቂሰ፡ ገበዝ supposed to be a title in the church hierarchy.

2023-02-01 16:29 UTC, eu-genia requested changes

2023-02-02 09:10 UTC, CarstenHoffmannMarburg commented on new/PRS13975BadaMaryam.xml
> +                    <floruit>1728</floruit>
Done.

2023-02-02 09:14 UTC, CarstenHoffmannMarburg commented on new/PRS13975BadaMaryam.xml
> +                    <faith type="EOTC"/>
Done: <name role="qesa gabaz">ቂሰ፡ ገበዝ፡</name>

2023-02-02 09:17 UTC, CarstenHoffmannMarburg commented on new/PRS13975BadaMaryam.xml
> +            </listPerson><!---->
None of that. He is mentioned in the colophon as being in charge when the manuscript (part1) was written. See: <colophon xml:id="coloph2"><locus from="122ra" to="122rb" xml:lang="gez"/>ተጽሕፈት፡ ዛቲ፡ መጽሐፍ፡ በዘመነ፡ ዮሐንስ፡ 
                                ወንጌላዊ፡ በ፸፻ወ፪፻፡ ፳ወ፰፡ ዓመተ፡ ዓለም፡ ወሠርቀ፡ ሌሊት፡ ፬፡ ወሠርቀ፡ መዓልት፡ ፳ወ፮፡ በዘመነ፡ ንጉሥነ፡ <persName ref="PRS2377Bakaffa">በካፋ፡</persName> 
                                ወጳጳስነ፡ <persName ref="PRS6072Krestodo">ክርስቶዶሉ፡</persName> ወመምሕርነሂ፡ <persName ref="PRS00000">መቃርዮስ፡</persName> 
                                ወቂሰ፡ ገበዝሂ፡ <persName ref="PRS00000">በዕዳ፡ ማርያም፡</persName> ወጸሐፊሃኒ፡ <persName role="scribe" ref="PRS13968Arsanyos">አርሳንዮስ፡</persName>
                                ዘተድባበ፡ በመንግሥተ፡ ሰማያት፡ አሜን። 
                                ዛቲ፡ መጽሐፍ፡ ተወጽነት፡ አመ፡ ረቡዑ፡ ለሐምሌ፡ ወተፈጸመት፡ በካልአይ፡ አመት፡ አመ፡ ፳ሀ፡ ለሕዳር፡ በዘመነ፡ <persName ref="PRS00000">ማቴዎስ</persName>።</colophon>

2023-02-02 09:19 UTC, CarstenHoffmannMarburg commented on new/PRS13975BadaMaryam.xml
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1"/>
l.  49: <persName xml:lang="gez" type="normalized" corresp="#n1">Bāʿda Māryām</persName>

2023-02-02 09:23 UTC, DenisNosnitsin1970 commented on new/PRS13975BadaMaryam.xml
> +            </listPerson><!---->
በዕዳ፡ ማርያም፡ is a senior ecclesiastic (qesa gabaz) of the church Tadbaba Maryam,` LOC5843Tadbab` , and mamher Maqaryos must be the abbot.

2023-02-02 09:34 UTC, CarstenHoffmannMarburg commented on new/PRS13975BadaMaryam.xml
> +            </listPerson><!---->
Do you think the name must be በዕዳ፡ ማርያም፡ ? In the manuscript it rather looks like ባዕደ፡

2023-02-02 09:35 UTC, CarstenHoffmannMarburg commented on new/PRS13975BadaMaryam.xml
> +            </listPerson><!---->
How can I note the church Tadbaba Maryam? Where is this information from?

2023-02-02 09:36 UTC, CarstenHoffmannMarburg commented on new/PRS13975BadaMaryam.xml
> +            </listPerson><!---->
How can I note this information?

2023-02-02 09:43 UTC, eu-genia commented on new/PRS13975BadaMaryam.xml
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1"/>
please fill it in the XML tag, not here.

2023-02-02 09:44 UTC, eu-genia commented on new/PRS13975BadaMaryam.xml
> +            </listPerson><!---->
The information (as @DenisNosnitsin1970 has provided) must be inserted in the `floruit `tag, it is very important to always provide as much data as possible for disambiguation (he is not the only Baeda Maryam in Ethiopia)

2023-02-02 09:46 UTC, eu-genia commented on new/PRS13975BadaMaryam.xml
> +            </listPerson><!---->
One can also mention (here, or marking up the colophon) that he was a contemporary of Bakaffa and Krestodolu III, even if this is clear from the date

2023-02-02 09:52 UTC, eu-genia requested changes

2023-02-02 09:52 UTC, eu-genia commented on new/PRS13975BadaMaryam.xml
> +                    <faith type="EOTC"/>
please check the Guidelines https://betamasaheft.eu/Guidelines/?q=roleName&id=roles on marking up `roleName`, we do not use the tag `name `at all

2023-02-02 09:52 UTC, eu-genia commented on new/PRS13975BadaMaryam.xml
> +                    <faith type="EOTC"/>
It should be `<persName><roleName type="office">ቂሰ፡ ገበዝ፡</roleName></persName>`

2023-02-02 09:52 UTC, eu-genia commented on new/PRS13975BadaMaryam.xml
> +                    <faith type="EOTC"/>
Please always use our Guidelines which have examples 
![image](https://user-images.githubusercontent.com/17987728/216291122-68637cd9-2f82-4c51-b896-409b669b0b6b.png)

and/or search other records
e.g.
![image](https://user-images.githubusercontent.com/17987728/216291613-22a4864b-ba84-4a4e-8486-70a5b6a7ecc8.png)


 if you are not sure how things must be encoded, Creative encoding may damage the application.
Thank you!

2023-02-02 09:52 UTC, eu-genia commented on new/PRS13975BadaMaryam.xml
> +            </listPerson><!---->
The information must still be inserted

2023-02-02 09:53 UTC, eu-genia commented on new/PRS13975BadaMaryam.xml
> +            </listPerson><!---->
Ok I see it now, thank you!

2023-02-02 09:57 UTC, CarstenHoffmannMarburg commented
Don't understand how to insert roleName.

2023-02-02 09:58 UTC, eu-genia requested changes

2023-02-02 09:58 UTC, eu-genia commented on new/PRS13975BadaMaryam.xml
> +                        <placeName ref="LOC5843">Tadbaba Maryam</placeName> in the time of abbot mamher
please provide the exact complete ID for Tadbaba Maryam

please transcribe mamher

2023-02-02 10:16 UTC, eu-genia requested changes

2023-02-02 10:16 UTC, eu-genia commented on new/PRS13975BadaMaryam.xml
> +            </listPerson><!---->
Thank you, note that Denis has agreed that adding the information on being a contemporary of Bakaffa and Krestodolu III would also be helpful.

2023-02-02 10:16 UTC, eu-genia commented on new/PRS13975BadaMaryam.xml
> +                        <placeName ref="LOC5843Tadbab">Tadbaba Maryam</placeName> in the time of abbot mamhər
Māryām

2023-02-02 10:16 UTC, eu-genia commented on new/PRS13975BadaMaryam.xml
>                      <birth/>
please correct the roleName  (just copypaste from my earlier comment)

2023-02-02 10:37 UTC, CarstenHoffmannMarburg commented
element "roleName" not allowed here.

2023-02-02 10:49 UTC, eu-genia approved these changes

2023-02-02 10:49 UTC, merged