Create PRS13991Alaryoan.xml
BetaMasaheft/Persons pull request #696
Opened 2023-03-26 03:11 UTC by DenisNosnitsin1970

A commissioner of Abb91.

2023-03-27 07:57 UTC, eu-genia requested changes

2023-03-27 07:57 UTC, eu-genia commented on new/PRS13991Alaryoan.xml
> +            <t:langUsage xmlns:t="http://www.tei-c.org/ns/1.0">
remove all `t: `prefixes, delete `"xmlns:t="http://www.tei-c.org/ns/1.0"`

2023-03-28 09:42 UTC, thea-m requested changes

2023-03-28 10:03 UTC, DenisNosnitsin1970 commented on new/PRS13991Alaryoan.xml
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1">Alarǝyoʾan</persName>
Indeed. Thanks!

2023-03-28 10:09 UTC, thea-m approved these changes

2023-03-28 10:11 UTC, merged