PRS14027ChristianBarth
BetaMasaheft/Persons pull request #721
Opened 2023-05-26 19:30 UTC by DenisNosnitsin1970

New record and minor corrections in another one.

2023-05-30 11:21 UTC, eu-genia requested changes

2023-05-30 11:21 UTC, eu-genia commented on new/PRS14027ChristianBarth.xml
> +                    <persName xml:lang="gez" xml:id="n1">Christian Gottlob Barth</persName>
lang=de

2023-05-30 11:21 UTC, eu-genia commented on new/PRS14027ChristianBarth.xml
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1"/>
delete line

2023-05-30 11:21 UTC, eu-genia commented on new/PRS14027ChristianBarth.xml
> +                    <persName xml:lang="gez" xml:id="n1">Christian Gottlob Barth</persName>
`<persName xml:lang="de" xml:id="n1"><forename>Christian</forename> <forename>Gottlob</forename> <surname>Barth</surname></persName>`

2023-08-14 16:32 UTC, thea-m requested changes

2023-08-14 16:32 UTC, thea-m commented on new/PRS14028HabtaMikael.xml
> +                <title>Habta Mikael</title>
transcription

2023-08-14 19:09 UTC, DenisNosnitsin1970 commented on new/PRS14027ChristianBarth.xml
> +                    <persName xml:lang="gez" xml:id="n1">Christian Gottlob Barth</persName>
ok

2023-08-14 19:11 UTC, DenisNosnitsin1970 commented on new/PRS14028HabtaMikael.xml
> +                <title>Habta Mikael</title>
ok

2023-08-16 09:56 UTC, eu-genia approved these changes

2023-08-16 11:21 UTC, merged