New PRS in EMML1832 (no.4)
BetaMasaheft/Persons pull request #789
Opened 2024-01-12 15:58 UTC by CarstenHoffmannMarburg

I created new PRS from EMML1832. The last four of them have been discussed in https://github.com/BetaMasaheft/Documentation/issues/2458.

2024-01-12 16:06 UTC, thea-m requested changes
Thank you! As I wrote in the issue, I am not convinced that the last four records here are persons. I think they might refer to places or other entities (e.g. māḫbar).

2024-01-12 16:06 UTC, thea-m commented on new/PRS14259BahaylaKrestos.xml
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1"/>
fidal lacking, fidal and transcription to be swapped

2024-01-12 16:06 UTC, thea-m commented on new/PRS14259BahaylaKrestos.xml
> +                    <relation name="lawd:hasAttestation" active="PRS14259BahaylaKrestos" passive=""/>
ms ID

2024-01-12 16:48 UTC, CarstenHoffmannMarburg commented
> Thank you! As I wrote in the issue, I am not convinced that the last four records here are persons. I think they might refer to places or other entities (e.g. māḫbar).

Yes, indeed, this name also sounds strange to me. As far as I have come across, there are a number of personal names that include the name Māḫbar as part of their name:
Tasfa Kokab Maḫbar (PRS9276TasfaKo)
Fǝre Māḫbar (PRS11144FereM, PRS4067FereMah, PRS12413FereMahbar)
Yamāna ʾAb Lāʾka Māḫbar (PRS13175YamanaA)
Takla Māḫbar (PRS11758TaklaMahbar)

I can imagine that the name Māḫbar in these names could be an allusion to the House of Christ = Church or the Temple in Jerusalem. It could also be an abbreviation of a combined name like one of the above.

2024-02-08 09:16 UTC, CarstenHoffmannMarburg commented
In this pull request, 6 out of 10 records are OK. But the last four records need to be deleted, because they are assumed to be placenames, that we decided not to mark up in the record. For this reason, this branch needs to be approved and merged and the four problematic records need to be deleted in a new pull request afterwards.

2024-02-08 13:33 UTC, eu-genia commented
I deleted
PRS14261Mahbar
PRS14262Zengita
PRS14263Wambaya
PRS14264Yalaela
on the backend so they can already be deleted in this branch

2024-02-08 15:58 UTC, eu-genia approved these changes

2024-02-12 10:39 UTC, thea-m approved these changes

2024-02-12 10:39 UTC, merged