PRS in EMML1832 (no.7)
BetaMasaheft/Persons pull request #791
Opened 2024-01-16 16:12 UTC by CarstenHoffmannMarburg

I have encoded personal names EMML1832 - namely 9 out of 12 names that we were able to identify as deacons in a note on incense from the 14th century, as discussed in https://github.com/BetaMasaheft/Documentation/issues/2458. 

However, there are three more entities in this list that should result in 12 people, which I have postponed because they are not without problems for me: 

1) ሐደራ -> the same name also appears in the list of countries immediately above. I do not know if this is a coincidence or if it is the same personal name in both cases. 
2) ዘበልዐ፡ ምድረ፡ <persName ref="PRS00000000000000">ልደታ፡ ለማርያም። is accompanied by the formula za-balʿa mǝdra which puzzled us so much.
 3) ዘበልዐ፡ ምድረ፡ <persName ref="PRS00000000000">መርቆርዮስ። The same formula again, and even the same name, which I have coded as PRS14268Marqoryos, but I happen not to be sincere as to whether it really is a personal name. If we do not find a flawless solution, I suggest we refrain from doing so and leave these three names without markup.

<img width="562" alt="Screenshot 2024_incense" src="https://github.com/BetaMasaheft/Persons/assets/40291787/f4f1fccc-aa4f-43db-b173-59416d9b3dc2">

2024-01-16 16:24 UTC, DenisNosnitsin1970 commented
ዘበልዐ፡ ምድረ፡ ልደታ፡ ለማርያም። I think this is someone (a clergyman) who receives tributes from the land meant for the feast of ልደታ፡ ለማርያም። "Who east (from.).." - to indicate exactly this relation. ምድረ፡ መርቆርዮስ። the same, the land for St Mercury feast. what is ሐደራ i do not know, frankly speaking. Also there are a few other where I am in doubt.

2024-02-08 09:36 UTC, CarstenHoffmannMarburg commented
A decision needs to be made whether or not we think that the 9 names in these files are indeed likely to be 14th century deacons, as I have encoded them here and in the manuscript record of EMML1832 (which is already merged). If the doubts are too great, it would be necessary to merge and delete these nine records in a new pull request and update EMML1832 accordingly.
```
<item xml:id="a3">
                           <locus from="2ra" to="3rb"/>
                           <desc type="Record">Order of incensing at the <placeName ref="INS0327DHE"/> made by ʿaqqābe saʿat 
                              <persName ref="PRS10374Yohanne"/>.</desc>
                           <q xml:lang="gez">
...
                              ወዲያቆናትሂ፡ ይኩን፡ ኍልቆሙ፡ ፲ወ፪፡ ላዕለ፡ ስመ፡ ንጹሓን፡ ሳባኪያን፡ ሩሃን፡ ፲ወ፪፡ ሐዋርያት። ክቡራን። ወአስማቲሆሙ፡ ከመዝ። 
                              <persName ref="PRS14277Mamas">ማማስ።</persName>
                              <persName ref="PRS14278AmlakMoa">አምላክ፡ ምአ።</persName> 
                              <persName ref="PRS14279AmlakaBena">አምላከ፡ ብነ።</persName> 
                              <persName ref="PRS14280Simeon">ስምዖን፡ </persName>
                              <persName ref="PRS14281Senoda">ሴኖዳ።</persName>
                              <persName ref="PRS14282YohannesKama">ዮሐንስ፡ ከማ።</persName> 
                              <persName ref="PRS14283YeheyyesTaameno">ይሄይስ፡ ተአምኖ።</persName> 
                              <persName ref="PRS14284Endreyas">እንድርያስ።</persName> 
                              ሐደራ።
                              ዘበልዐ፡ ምድረ፡ ልደታ፡ ለማርያም። 
                              ዘበልዐ፡ ምድረ፡ መርቆርዮስ። 
                              <persName ref="PRS14285ZaraBuruk">ዘርአ፡ ቡሩክ። ።</persName></q>
                        </item>
```

2024-04-16 15:57 UTC, CarstenHoffmannMarburg commented
Can this branch with 9 files be merged?

2024-04-18 20:16 UTC, eu-genia requested changes

2024-04-18 20:16 UTC, eu-genia commented on new/PRS14279AmlakaBena.xml
> +                    <floruit notBefore="1320" notAfter="1400">14th</floruit>
14th century

2024-04-18 20:16 UTC, eu-genia commented on new/PRS14278AmlakMoa.xml
> +                    <floruit notBefore="1320" notAfter="1400">14th</floruit>
14th century

2024-04-18 20:16 UTC, eu-genia commented on new/PRS14277Mamas.xml
> +                    <floruit notBefore="1320" notAfter="1400">14th</floruit>
14th century

2024-04-18 20:16 UTC, eu-genia commented on new/PRS14280Simeon.xml
> +                    <floruit notBefore="1320" notAfter="1400">14th</floruit>
cent

2024-04-18 20:16 UTC, eu-genia commented on new/PRS14281Senoda.xml
> +                    <floruit notBefore="1320" notAfter="1400">14th</floruit>
cent

2024-04-18 20:16 UTC, eu-genia commented on new/PRS14282YohannesKama.xml
> +                    <floruit notBefore="1320" notAfter="1400">14th</floruit>
cent

2024-04-18 20:16 UTC, eu-genia commented on new/PRS14283YeheyyesTaameno.xml
> +                    <floruit notBefore="1320" notAfter="1400">14th</floruit>
cent

2024-04-18 20:16 UTC, eu-genia commented on new/PRS14284Endreyas.xml
> +                    <floruit notBefore="1320" notAfter="1400">14th</floruit>
cent

2024-04-18 20:16 UTC, eu-genia commented on new/PRS14285ZaraBuruk.xml
> +                    <floruit notBefore="1320" notAfter="1400">14th</floruit>
cent

2024-06-01 00:50 UTC, merged