PRS in EMML1832 (no.8)
BetaMasaheft/Persons pull request #793
Opened 2024-01-23 13:50 UTC by CarstenHoffmannMarburg

Various PRS in additions in EMML1832.

2024-01-24 08:32 UTC, thea-m requested changes
Thank you!

2024-01-24 08:32 UTC, thea-m commented on new/PRS14287Mangaday.xml
> +                    <occupation type="ecclesiastic">qamaẓānay (= liqa maẓāne)</occupation>
is ẓ used here for ḍ (which has to be used according to the guidelines)?

2024-01-24 08:32 UTC, thea-m commented on new/PRS14287Mangaday.xml
> +            <t:langUsage xmlns:t="http://www.tei-c.org/ns/1.0">
"t:...xmlns:t="http://www.tei-c.org/ns/1.0"" sneaked in again...could you delete it?

2024-01-24 08:32 UTC, thea-m commented on new/PRS14289Matewos.xml
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1"/>
filda missing and to be swapped

2024-01-24 08:32 UTC, thea-m commented on new/PRS14294Zakkaryas.xml
> +                    <relation name="snap:UncleOf" active="PRS14294Zakkaryas" passive="PRS00000000000000"/>
record still missing?

2024-01-24 08:32 UTC, thea-m commented on new/PRS14296Kiros.xml
> +                    <persName xml:lang="gez" xml:id="n1"></persName>
fidal missing

2024-01-24 12:28 UTC, thea-m approved these changes

2024-01-25 08:48 UTC, eu-genia approved these changes

2024-01-25 08:49 UTC, merged