New PRS in EMML1832 (no.10)
BetaMasaheft/Persons pull request #795
Opened 2024-01-25 16:17 UTC by CarstenHoffmannMarburg

I created new PRS IDs for personal names that I found in EMML1832. However, I found an existing ID for Yǝʿqabanna, who is documented probably as a pretender to the thrown in the time of Yāgbǝʿ Ṣyon. I did not find any references or relations connected to PRS10327Yeqaba before I rendered it. The record is probably from EAe (that I cannot check at the moment) or from another secondary literature source.

2024-01-26 13:35 UTC, eu-genia approved these changes

2024-01-26 13:56 UTC, thea-m requested changes
Thank you, very nice!

2024-01-26 13:56 UTC, thea-m commented on new/PRS14309Benyam.xml
> +                    <persName xml:lang="gez" xml:id="n1">Bǝnyām</persName>
fidal missing and to be swapped

2024-01-26 13:56 UTC, thea-m commented on new/PRS14311AmlakBena.xml
> +                        person as <persName ref="PRS14279AmlakaBena"/>, who was mentioned as a deacon in a previous addition.</desc></relation>
I think that "in a previous addition" might not be a clear formulation to any readers who only see the person record and not the manuscript.

2024-01-29 10:47 UTC, thea-m approved these changes

2024-01-29 10:48 UTC, merged

2024-01-29 11:02 UTC, eu-genia commented
nb if you notice that the server is down please do not merge, these merges have no chance of making it to the app and have to be repeated, thank you