Create PRS14317Rowe
BetaMasaheft/Persons pull request #804
Opened 2024-02-05 09:16 UTC by CarstenHoffmannMarburg

I created a record for W.G.H. Lowe (!), who sold the manuscript BLorient11601 to the BM (=BL).

2024-02-05 09:35 UTC, eu-genia commented on new/PRS14317Rowe.xml
> +                </person>
he may have been a jeweller from Canada https://archive.org/stream/jewelerscircular00unse_64/jewelerscircular00unse_64_djvu.txt, one of the directors of the Commercial Travellers Association of Montreal https://numerique.banq.qc.ca/patrimoine/details/52327/4235959?docsearchtext=w.g.h.%20lowe (elected 1884) and member of the local masonic lodge; he died on 3 February 1904  https://dokumen.tips/document/proceedings-grand-lodge-of-af-am-of-canada-1904.html?page=336

2024-02-06 11:16 UTC, CarstenHoffmannMarburg commented
I have no problem with creating zotero tags for the secondary literature investigated by Eugenia. Quoting the links may be not ideal, because it frequently causes problems with expired links.

2024-02-06 12:35 UTC, thea-m requested changes
Thank you!

2024-02-06 12:35 UTC, thea-m commented on new/PRS14317Rowe.xml
> +                        <bibl><ptr target="bm:bm:TheTrader1885LoweAnderson"/></bibl>,
bm:bm

2024-02-06 17:52 UTC, thea-m approved these changes

2024-02-06 17:52 UTC, merged