Create PRS14369Clarkes for BLorient8815
BetaMasaheft/Persons pull request #832
Opened 2024-03-14 11:23 UTC by CarstenHoffmannMarburg

According to Strelcyn, the name is given in the manuscript as following: "Dr. Clarkes MS. T.Y.". 

I hope, it is not too speculative to interprete MS. as 'Master of Science' and T. Y. as abbreviation of forenames.

2024-03-14 12:13 UTC, eu-genia requested changes

2024-03-14 12:13 UTC, eu-genia commented on new/PRS14369Clarkes.xml
> +                    <persName xml:lang="gez" xml:id="n1"><forename>T.</forename> <forename>Y.</forename>
en

2024-03-14 12:13 UTC, eu-genia commented on new/PRS14369Clarkes.xml
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1"/>
remove line

2024-03-18 13:52 UTC, thea-m approved these changes

2024-03-18 13:52 UTC, merged