Addisie Marigeta damse endalew
BetaMasaheft/Persons pull request #851
Opened 2024-04-26 14:02 UTC by Addisie

2024-04-26 14:19 UTC, thea-m approved these changes
very nice, thank you!

2024-04-26 19:45 UTC, eu-genia requested changes
thank you!

2024-04-26 19:45 UTC, eu-genia commented on new/PRS14417MarigetaDamseEndalew.xml
> +                    <occupation type="literary">He is a private professional scribe since
is ---> has been

2024-04-26 19:45 UTC, eu-genia commented on new/PRS14417MarigetaDamseEndalew.xml
> +                    </placeName> in <date when="1985"/> since then he has been teaching Dǝggʷā at<placeName ref="LOC2386DabraT">
space after at

2024-04-26 19:45 UTC, eu-genia commented on new/PRS14417MarigetaDamseEndalew.xml
> +                    <occupation type="literary">He is a private professional scribe since
add 
`as of 2024`

2024-04-26 22:08 UTC, eu-genia approved these changes

2024-04-26 23:47 UTC, eu-genia commented
thank you, all is good, but unfortunately the application is down so I would like to wait with merging any PRs for the moment

2024-04-29 06:39 UTC, CarstenHoffmannMarburg commented on new/PRS14417MarigetaDamseEndalew.xml
> +                    <persName><roleName type="title">Marigetā</roleName></persName>
In contrast to common practice and to distinguish them from the names, we usually write titles in small letters: marigetā

2024-04-29 06:39 UTC, CarstenHoffmannMarburg commented on new/PRS14417MarigetaDamseEndalew.xml
> +                        <date when="1980"/> as of 2024.</occupation>
comma before as

2024-04-29 06:39 UTC, CarstenHoffmannMarburg commented on new/PRS14417MarigetaDamseEndalew.xml
> +                    </placeName> in <date when="1985"/> since then he has been teaching Dǝggʷā at <placeName ref="LOC2386DabraT">
Split sentence: "... . Since then"

2024-04-30 02:02 UTC, merged