Create PRS in BLorient12860
BetaMasaheft/Persons pull request #873
Opened 2024-06-17 06:30 UTC by CarstenHoffmannMarburg

I created record for two persons, that are mentioned in BLorient12860 - both most probably as owners. For Marius Bernard, I assume that it is the author of various orientalist books (wd:Q110089719). However, he is mentioned in the manuscript with his title "Angelus Comnenus", but I was not able to verify this title for Q110089719.

For Т. Печагуев, I did not find any information. I assume, that it is a Russian name, but it can also be Serbian, Bulgarian or Ukrainian.

2024-06-17 10:40 UTC, DenisNosnitsin1970 requested changes

2024-06-17 10:40 UTC, DenisNosnitsin1970 commented on new/PRS14477Pechaguev.xml
> +                <title>Т. Печагуев</title>
I assume the title should be rather the Latin transcription, Cyrillic can be one of the versions (cp. PRS6062Krackovs).

2024-06-17 10:40 UTC, DenisNosnitsin1970 commented on new/PRS14477Pechaguev.xml
> +                <language ident="ru">Russian</language>
No `<floruit/>`?

2024-09-09 19:27 UTC, eu-genia approved these changes

2024-10-23 16:32 UTC, merged