Create PRS14428Abreham.xml
BetaMasaheft/Persons pull request #877
Opened 2024-06-27 19:27 UTC by MarcinKrawczuk

2024-06-28 05:12 UTC, CarstenHoffmannMarburg requested changes

2024-06-28 05:12 UTC, CarstenHoffmannMarburg commented on new/PRS14428Abreham.xml
> +                    <floruit/>
Is it possible to determine the approximate floruit? This could be wide or narrow.

2024-06-28 18:31 UTC, MarcinKrawczuk commented
Of course, added after palaeographic features of the ms. (at least to my
judgement... )

pt., 28 cze 2024 o 07:12 Carsten Hoffmann ***@***.***>
napisał(a):

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In new/PRS14428Abreham.xml
> <https://github.com/BetaMasaheft/Persons/pull/877#discussion_r1658152055>:
>
> > +            </langUsage>
> +        </profileDesc>
> +        <revisionDesc>
> +            <change who="MKr" when="2024-06-27">Created entity</change>
> +        </revisionDesc>
> +    </teiHeader>
> +    <text>
> +        <body>
> +            <listPerson>
> +                <person sex="1">
> +                    <persName xml:lang="gez" xml:id="n1">አብርሃም፡</persName>
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1">ʾAbrǝhām</persName>
> +                    <faith type="EOTC"/>
> +                    <birth/>
> +                    <death/>
> +                    <floruit/>
>
> Is it possible to determine the approximate floruit? This could be wide or
> narrow.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Persons/pull/877#pullrequestreview-2147050832>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJTK555QKBQXNDAWLVLZJTWE3AVCNFSM6AAAAABKARIP3SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNBXGA2TAOBTGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-01 08:29 UTC, CarstenHoffmannMarburg commented on new/PRS14428Abreham.xml
> +                    <floruit notBefore="1350" notAfter="1500"/>
It is even nicer, if the date in floruit is expressed also verbally, i.e.:
`<floruit notBefore="1350" notAfter="1500">Second half of 14th to 15th century</floruit>`

2024-07-01 08:29 UTC, CarstenHoffmannMarburg approved these changes

2024-07-02 17:28 UTC, CarstenHoffmannMarburg approved these changes

2024-07-02 17:38 UTC, merged