PRS14489
BetaMasaheft/Persons pull request #878
Opened 2024-07-01 16:03 UTC by DenisNosnitsin1970

One new record, changes in two others (dissimilations of scribes with the same name).

2024-07-03 09:28 UTC, eu-genia requested changes

2024-07-03 09:28 UTC, eu-genia commented on PRS12001-13000/PRS12076ZawaldaMaryam.xml
> +                    <relation name="saws:isCopierOf" active="PRS12076ZawaldaMaryam" passive="ESqsm001 ESqsm007 ESmr008 ESmr033 ESmkl015 ESmkl016 BMLacq810 BMLacq306"/>
split

2024-07-03 20:48 UTC, DenisNosnitsin1970 commented on PRS12001-13000/PRS12076ZawaldaMaryam.xml
> +                    <relation name="saws:isCopierOf" active="PRS12076ZawaldaMaryam" passive="ESqsm001 ESqsm007 ESmr008 ESmr033 ESmkl015 ESmkl016 BMLacq810 BMLacq306"/>
Like this?

2024-07-04 09:32 UTC, eu-genia commented on PRS12001-13000/PRS12076ZawaldaMaryam.xml
> +                    <relation name="saws:isCopierOf" active="PRS12076ZawaldaMaryam" passive="ESqsm001 ESqsm007 ESmr008 ESmr033 ESmkl015 ESmkl016 BMLacq810 BMLacq306"/>
```
<relation name="saws:isCopierOf" active="PRS12076ZawaldaMaryam" passive="ESqsm001"/>
<relation name="saws:isCopierOf" active="PRS12076ZawaldaMaryam" passive="ESqsm007"/>
<relation name="saws:isCopierOf" active="PRS12076ZawaldaMaryam" passive="ESmr008"/>
<relation name="saws:isCopierOf" active="PRS12076ZawaldaMaryam" passive="ESmr033"/>
etc
```

2024-07-04 09:40 UTC, merged