Create LIT14505Alamayahu (prince)
BetaMasaheft/Persons pull request #890
Opened 2024-07-23 09:08 UTC by CarstenHoffmannMarburg

2024-07-23 10:45 UTC, karljonaskarlsson commented
I am almost certain that this is the same person as PRS1625Alamayy, as he seems to be the only ʿĀlamāyyahu Tewodros in the EAe. It would, however, be good to expand that record, adding, for example, a reference to this book: https://thehistorypress.co.uk/publication/the-prince-and-the-plunder/

2024-07-23 11:47 UTC, DenisNosnitsin1970 requested changes

2024-07-23 11:47 UTC, DenisNosnitsin1970 commented on new/PRS14505Alamayahu.xml
> +                <title>ʿAlamāyahu Tewodros</title>
It is ʿAlamāyyahu.

2024-07-23 11:52 UTC, DenisNosnitsin1970 commented
Anyone who wants to expend the bibliogaphy is kinldy invited to do that :) However, the book by Andrew Heavens would be not good as the only one, if at all (the author has worked  "six years as a reporter and photographer in Ethiopia and Sudan", has no academic background. there can be hardly any doubt as to how the story is presented).

2024-07-23 12:02 UTC, CarstenHoffmannMarburg commented
> I am almost certain that this is the same person as PRS1625Alamayy, as he seems to be the only ʿĀlamāyyahu Tewodros in the EAe.

Sorry for not investigating it enough! I will update PRS1625Alamayy and delete PRS14505Alamayahu in a minute.

2024-07-23 12:05 UTC, DenisNosnitsin1970 commented
All people etc from the index of EAe have been converted to records, frequently really difficult to discover. 
:( (you have to resort to EAE spelling)

2024-07-23 12:19 UTC, karljonaskarlsson approved these changes

2024-09-18 12:48 UTC, eu-genia commented
It is correct that Prince Alamayyahu is PRS1625Alamayy and LIT14505Alamayahu is an error, I will merge as is BUT FOR THE FUTURE please - if you create a record through the web app you MUST first merge and THEN delete, as only then it will be deleted in the application.

Every time you create a record through the web app the stub with the ID is stored on the server, invisible to the GitHub repository. So when you create it and do not merge in order to sync the server and the GitHub repo it still remains there - still visible on the web but unavailable in GitHub.

2024-09-18 12:49 UTC, merged

2024-09-18 12:50 UTC, eu-genia commented
For a quick check to what has been inherited from EAe you can also use the spreadsheets at https://docs.google.com/spreadsheets/d/1a0LtliOVuXoRcDhgj3p5V1Z2i-M5k5_MkT6YgPgh04s/edit?usp=sharing