Create PRS14532WaldaKiros.xml
BetaMasaheft/Persons pull request #896
Opened 2024-07-31 20:10 UTC by DenisNosnitsin1970

An person mention in Abb. 186.

2024-08-01 07:27 UTC, CarstenHoffmannMarburg requested changes

2024-08-01 07:27 UTC, CarstenHoffmannMarburg commented on new/PRS14532WaldaKiros.xml
> +                    <relation name="saws:hasOwned" active="PRS14532WaldaKiros" passive="BNFabb186_"/>
Remove underscore (_) in `passive="BNFabb186_`.

2024-08-02 07:43 UTC, CarstenHoffmannMarburg approved these changes

2024-08-15 10:56 UTC, eu-genia approved these changes

2024-08-15 10:56 UTC, merged