2024 09 16 PRSs in uub o etiop 20
BetaMasaheft/Persons pull request #916
Opened 2024-09-17 13:49 UTC by karljonaskarlsson

2024-09-17 13:55 UTC, nafisa-valieva commented on new/PRS14565ErlingEidem.xml
Looks a fine person for me!

2024-09-17 13:57 UTC, nafisa-valieva commented on new/PRS14566ZawaldaMaryam.xml
All Zawalda Maryams are welcome, but it would be helpful to understand exactly what to do with the preexisting ones!

2024-09-18 06:54 UTC, CarstenHoffmannMarburg approved these changes

2024-09-18 07:01 UTC, eu-genia requested changes

2024-09-18 07:01 UTC, eu-genia commented on new/PRS14565ErlingEidem.xml
> +                    <persName xml:lang="gez" xml:id="n1">Erling Eidem</persName>
xml:lang="sv"
mark down `forename `and `surname`

2024-09-18 07:01 UTC, eu-genia commented on new/PRS14565ErlingEidem.xml
> +                <language ident="gez">Gǝʿǝz</language>
remove gez add sv

2024-09-18 07:01 UTC, eu-genia commented on new/PRS14566ZawaldaMaryam.xml
> +                    <floruit>1682–1694</floruit>
better add dates to attributes `notBefore ``notAfter `to make them filtrable

2024-09-18 10:58 UTC, eu-genia commented on new/PRS14566ZawaldaMaryam.xml
As long as you have no proof that this Zawalda Maryam is the same as any of the existing ones you must create a new record.
A record corresponds to a person, not to a name.

2024-09-18 13:32 UTC, eu-genia commented on new/PRS14566ZawaldaMaryam.xml
(this was for @nafisa-valieva :) )

> All Zawalda Maryams are welcome, but it would be helpful to understand exactly what to do with the preexisting ones!

2024-09-18 13:32 UTC, eu-genia approved these changes

2024-09-18 13:33 UTC, merged