Prs14573 hara krestos
BetaMasaheft/Persons pull request #921
Opened 2024-09-26 18:47 UTC by MarcinKrawczuk

Floruit after the date of the text part which he wrote.

BTW Zhenia told me to switch to Oxygen from Atom, I hope everyting is correct.

2024-09-26 19:04 UTC, CarstenHoffmannMarburg requested changes

2024-09-26 19:15 UTC, MarcinKrawczuk commented
OK, done, thank you very much.

czw., 26 wrz 2024 o 21:04 Carsten Hoffmann ***@***.***>
napisał(a):

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In new/PRS14573HaraKrestos.xml
> <https://github.com/BetaMasaheft/Persons/pull/921#discussion_r1777601059>:
>
> > +        </revisionDesc>
> +    </teiHeader>
> +    <text>
> +        <body>
> +            <listPerson>
> +                <person sex="1">
> +                    <persName xml:lang="gez" xml:id="n1">ሐራ፡ ክርስቶስ፡</persName>
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1">Ḥara Krǝstos</persName>
> +                    <faith type="EOTC"/>
> +                    <nationality type="Ethiopia"/>
> +                    <birth/>
> +                    <death/>
> +                    <floruit  notBefore="1400" notAfter="1500"></floruit>
> +                </person>
> +                <listRelation>
> +                    <relation name="saws:hasWritten" active="PRS14573HaraKrestos" passive="BNFabb94"/>
>
> I have seen, that saws:hasWritten is reserved to marginal parts. I think
> for the manuscript at large, we use saws:isCopierOf.
>
> @eu-genia <https://github.com/eu-genia> Is that correct?
> ------------------------------
>
> In new/PRS14573HaraKrestos.xml
> <https://github.com/BetaMasaheft/Persons/pull/921#discussion_r1777602496>:
>
> > +            </abstract>
> +            <langUsage>
> +                <language ident="en">English</language>
> +                <language ident="gez">Gǝʿǝz</language>
> +            </langUsage>
> +        </profileDesc>
> +        <revisionDesc>
> +            <change who="MKr" when="2024-09-23">Created entity</change>
> +        </revisionDesc>
> +    </teiHeader>
> +    <text>
> +        <body>
> +            <listPerson>
> +                <person sex="1">
> +                    <persName xml:lang="gez" xml:id="n1">ሐራ፡ ክርስቶስ፡</persName>
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1">Ḥara Krǝstos</persName>
>
> Ḥarā (corresponding to ሐራ)
> ------------------------------
>
> In new/PRS14573HaraKrestos.xml
> <https://github.com/BetaMasaheft/Persons/pull/921#discussion_r1777604823>:
>
> > +        </revisionDesc>
> +    </teiHeader>
> +    <text>
> +        <body>
> +            <listPerson>
> +                <person sex="1">
> +                    <persName xml:lang="gez" xml:id="n1">ሐራ፡ ክርስቶስ፡</persName>
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1">Ḥara Krǝstos</persName>
> +                    <faith type="EOTC"/>
> +                    <nationality type="Ethiopia"/>
> +                    <birth/>
> +                    <death/>
> +                    <floruit  notBefore="1400" notAfter="1500"></floruit>
> +                </person>
> +                <listRelation>
> +                    <relation name="saws:hasWritten" active="PRS14573HaraKrestos" passive="BNFabb94"/>
>
> Can you specify the textpart, i.e. BNFabb94#ms_i1?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Persons/pull/921#pullrequestreview-2332128604>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJU7CKFGBR2KB7TPCI3ZYRLETAVCNFSM6AAAAABO5UGLZCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMZSGEZDQNRQGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-26 19:16 UTC, eu-genia commented on new/PRS14573HaraKrestos.xml
> +                    <relation name="saws:hasWritten" active="PRS14573HaraKrestos" passive="BNFabb94"/>
> I have seen, that saws:hasWritten is reserved to marginal parts. I think for the manuscript at large, we use saws:isCopierOf.
> 
> @eu-genia Is that correct?

yes

2024-09-27 07:53 UTC, CarstenHoffmannMarburg approved these changes

2024-09-27 07:57 UTC, merged