Dastaw damda
BetaMasaheft/Persons pull request #922
Opened 2024-09-30 12:10 UTC by Addisie

2024-09-30 19:09 UTC, CarstenHoffmannMarburg requested changes

2024-09-30 19:09 UTC, CarstenHoffmannMarburg commented on new/PRS14567Dastaw.xml
> +                        <placeName ref="LOC2385DabraT">Dabra Tābor</placeName></birth>
He was born in 1990 E.C. in <placeName ref="LOC2385DabraT">Dabra Tābor</placeName>.

2024-10-01 09:22 UTC, eu-genia requested changes

2024-10-01 09:22 UTC, eu-genia commented on new/PRS14567Dastaw.xml
> +                    <persName xml:lang="gez" xml:id="n1">ደስታው፡ </persName>
Since we know it I would add the patronymic, Damḍa

2024-10-01 11:33 UTC, CarstenHoffmannMarburg approved these changes

2024-10-01 11:47 UTC, eu-genia commented on new/PRS14567Dastaw.xml
> +                    <persName xml:lang="gez" corresp="#n3" type="normalized">Damḍa</persName>
this is not what I meant ) I actually meant the normal way, as we usually refer to people
```
 <persName xml:lang="gez" xml:id="n1">ደስታው፡ ደምፀ፡</persName>
                    <persName xml:lang="gez" type="normalized" corresp="#n1">Dastāw Damḍa</persName>
```

2024-10-01 21:04 UTC, eu-genia approved these changes

2024-10-01 21:04 UTC, merged