Prs1295 abreham corr mk16.10 2024
BetaMasaheft/Persons pull request #947
Opened 2024-10-26 19:01 UTC by MarcinKrawczuk

2024-10-28 07:45 UTC, CarstenHoffmannMarburg requested changes

2024-10-28 07:45 UTC, CarstenHoffmannMarburg commented on PRS1001-2000/PRS1295Abreham.xml
> +               <persName>ʾ Abrǝhām of Dabra Ṣǝyon</persName>
ʾAbrǝhām (remove space between ʾ A)

2024-10-28 07:45 UTC, CarstenHoffmannMarburg commented on PRS1001-2000/PRS1295Abreham.xml
> +               <floruit notBefore="1350" notAfter="1450">He was active uduring the reign of ʾaṣe <persName ref="PRS3429DawitII">Dāwit</persName> and died during the reign of  ase <persName ref="PRS10
during, ʾaṣe/ʾaḍe

2024-10-28 18:24 UTC, MarcinKrawczuk commented
Thanks, corrected!

pon., 28 paź 2024 o 08:46 Carsten Hoffmann ***@***.***>
napisał(a):

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In PRS1001-2000/PRS1295Abreham.xml
> <https://github.com/BetaMasaheft/Persons/pull/947#discussion_r1818511298>:
>
> >        </revisionDesc>
>     </teiHeader>
>     <text xml:base="https://betamasaheft.eu/">
>        <body>
>           <listPerson>
>              <person sex="1">
> -               <persName>
> -
> -                  Abrǝhām of Dabra Ṣǝyon
> -               </persName>
> -               <!-- St.-->
> -               <residence>
> -                  Dabra Ṣǝyon
> -               </residence>
> +               <persName>ʾ Abrǝhām of Dabra Ṣǝyon</persName>
>
> ʾAbrǝhām (remove space between ʾ A)
> ------------------------------
>
> In PRS1001-2000/PRS1295Abreham.xml
> <https://github.com/BetaMasaheft/Persons/pull/947#discussion_r1818512286>:
>
> >        </revisionDesc>
>     </teiHeader>
>     <text xml:base="https://betamasaheft.eu/">
>        <body>
>           <listPerson>
>              <person sex="1">
> -               <persName>
> -
> -                  Abrǝhām of Dabra Ṣǝyon
> -               </persName>
> -               <!-- St.-->
> -               <residence>
> -                  Dabra Ṣǝyon
> -               </residence>
> +               <persName>ʾ Abrǝhām of Dabra Ṣǝyon</persName>
> +               <residence ref="LOC2372DabraS">Dabra Ṣǝyon</residence>
> +               <nationality type="Ethiopia"></nationality>
> +               <faith type="EOTC"></faith>
> +               <floruit notBefore="1350" notAfter="1450">He was active uduring the reign of ʾaṣe <persName ref="PRS3429DawitII">Dāwit</persName> and died during the reign of  ase <persName ref="PRS10342Yeshaq">Yǝsḥāq</persName>.</floruit>
>
> during, ʾaṣe/ʾaḍe
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Persons/pull/947#pullrequestreview-2398169691>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJS5DKQYCNUFIORTVU3Z5XMS7AVCNFSM6AAAAABQVBRNJGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOJYGE3DSNRZGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-29 06:24 UTC, CarstenHoffmannMarburg approved these changes

2024-10-29 07:11 UTC, merged