Addisie marigetā čakola
BetaMasaheft/Persons pull request #950
Opened 2024-11-06 14:31 UTC by Addisie

2024-11-06 17:03 UTC, CarstenHoffmannMarburg requested changes

2024-11-06 17:03 UTC, CarstenHoffmannMarburg commented on new/PRS14581MarigetaCakola.xml
> +                    <relation name="snap:FatherOf" active="PRS14581MarigetaCakola" passive="PRS14417MarigetaDamseEndalew"/>
You stated, that he is his maternal grandfather in https://github.com/BetaMasaheft/Manuscripts/pull/2679/files.

2024-11-06 17:03 UTC, CarstenHoffmannMarburg commented
Thank you!

2024-11-07 17:44 UTC, CarstenHoffmannMarburg approved these changes

2024-11-07 22:18 UTC, eu-genia approved these changes
thank you
for the future please avoid diacritics in the names of branches (this one is  `Addisie-Marigetā-Čakola` with 2 non-ASCII symbols)

2024-11-15 12:38 UTC, merged