Prs14582 theodorus
BetaMasaheft/Persons pull request #952
Opened 2024-11-07 22:11 UTC by MarcinKrawczuk

In the case of non-Ethiopian persons with a Wikidata link I usually give very little info. If you think that sth should be added, let me know.

2024-11-08 09:01 UTC, CarstenHoffmannMarburg commented
Well done! Thank you!

2024-11-08 09:03 UTC, CarstenHoffmannMarburg requested changes

2024-11-08 09:03 UTC, CarstenHoffmannMarburg commented on new/PRS14582Theodorus.xml
> +                <person sameAs="Q770191" sex="1">
I think, you have to give it as sameAs="wd:Q770191"

2024-11-08 17:58 UTC, MarcinKrawczuk commented
Done in both records.

pt., 8 lis 2024 o 10:03 Carsten Hoffmann ***@***.***>
napisał(a):

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In new/PRS14582Theodorus.xml
> <https://github.com/BetaMasaheft/Persons/pull/952#discussion_r1833968107>:
>
> > +            <abstract>
> +                <p/>
> +            </abstract>
> +            <langUsage>
> +                <language ident="en">English</language>
> +                <language ident="gez">Gǝʿǝz</language>
> +            </langUsage>
> +        </profileDesc>
> +        <revisionDesc>
> +            <change who="MKr" when="2024-11-06">Created entity</change>
> +        </revisionDesc>
> +    </teiHeader>
> +    <text>
> +        <body>
> +            <listPerson>
> +                <person sameAs="Q770191" sex="1">
>
> I think, you have to give it as sameAs="wd:Q770191"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Persons/pull/952#pullrequestreview-2423125167>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJV7M2SWXFC43MWIXK3Z7R46PAVCNFSM6AAAAABRMGNLQ6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMRTGEZDKMJWG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-11 08:58 UTC, CarstenHoffmannMarburg approved these changes

2024-11-11 11:21 UTC, merged