Persons for emml1844
BetaMasaheft/Persons pull request #958
Opened 2024-11-12 17:33 UTC by MarcinKrawczuk

There are three files here for persons attested in EMML 1844 (the dates in floruit after the approximate date of the mss).

2024-11-13 10:49 UTC, CarstenHoffmannMarburg commented on new/PRS14590Matyas.xml
> +                        sometimes together with "his brother" <ref type="pers" corresp="PRS14591Yeshaq">Yǝsḥaq</ref>.</floruit>
If you can add these manuscripts in the relations, it would be a great improvement.

2024-11-13 10:51 UTC, CarstenHoffmannMarburg requested changes

2024-11-13 10:51 UTC, CarstenHoffmannMarburg commented on new/PRS14591Yeshaq.xml
> +                <title>Yǝsḥaq</title>
ṣ

2024-11-13 10:51 UTC, CarstenHoffmannMarburg commented on new/PRS14591Yeshaq.xml
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1">Yǝsḥaq</persName>
ṣ

2024-11-13 10:51 UTC, CarstenHoffmannMarburg commented on new/PRS14591Yeshaq.xml
> +                        sometimes together with "his brother" <ref type="pers" corresp="PRS14590Matyas">Mātyās</ref>.</floruit>
If you can add also the IDs of the other manuscripts in relation, it would be an important improvement.

2024-11-13 11:18 UTC, MarcinKrawczuk commented
Sure, which relation would you advise me to use for Yeshaq and Matyas i. e.
patrons / sponsors (ዘአጽሐፈ:)?

śr., 13 lis 2024 o 11:51 Carsten Hoffmann ***@***.***>
napisał(a):

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In new/PRS14591Yeshaq.xml
> <https://github.com/BetaMasaheft/Persons/pull/958#discussion_r1839966280>:
>
> > @@ -0,0 +1,63 @@
> +<?xml-model href="https://raw.githubusercontent.com/BetaMasaheft/schema/master/tei-betamesaheft.rng"
> +schematypens="http://relaxng.org/ns/structure/1.0"?><?xml-model href="https://raw.githubusercontent.com/BetaMasaheft/schema/master/tei-betamesaheft.rng"
> +type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
> +<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="PRS14591Yeshaq" xml:lang="en" type="pers">
> +    <teiHeader>
> +        <fileDesc>
> +            <titleStmt>
> +                <title>Yǝsḥaq</title>
>
> ṣ
> ------------------------------
>
> In new/PRS14591Yeshaq.xml
> <https://github.com/BetaMasaheft/Persons/pull/958#discussion_r1839966651>:
>
> > +            </abstract>
> +            <langUsage>
> +                <language ident="en">English</language>
> +                <language ident="gez">Gǝʿǝz</language>
> +            </langUsage>
> +        </profileDesc>
> +        <revisionDesc>
> +            <change who="MKr" when="2024-11-11">Created entity</change>
> +        </revisionDesc>
> +    </teiHeader>
> +    <text>
> +        <body>
> +            <listPerson>
> +                <person sex="1">
> +                    <persName xml:lang="gez" xml:id="n1">ይጽሐቅ፡</persName>
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1">Yǝsḥaq</persName>
>
> ṣ
> ------------------------------
>
> In new/PRS14591Yeshaq.xml
> <https://github.com/BetaMasaheft/Persons/pull/958#discussion_r1839967825>:
>
> > +        <revisionDesc>
> +            <change who="MKr" when="2024-11-11">Created entity</change>
> +        </revisionDesc>
> +    </teiHeader>
> +    <text>
> +        <body>
> +            <listPerson>
> +                <person sex="1">
> +                    <persName xml:lang="gez" xml:id="n1">ይጽሐቅ፡</persName>
> +                    <persName xml:lang="gez" type="normalized" corresp="#n1">Yǝsḥaq</persName>
> +                    <faith type="EOTC"/>
> +                    <nationality type="Ethiopia"/>
> +                    <birth/>
> +                    <death/>
> +                    <floruit notBefore="1500" notAfter="1599">He is recorded as the commissioner of a few 16th-Century manuscripts from <ref type="ins" corresp="INS0327DHE">Dabra Ḥayq ʾƎsṭifānos</ref>,
> +                        sometimes together with "his brother" <ref type="pers" corresp="PRS14590Matyas">Mātyās</ref>.</floruit>
>
> If you can add also the IDs of the other manuscripts in relation, it would
> be an important improvement.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Persons/pull/958#pullrequestreview-2432643474>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJVI536JUJT7ZX7IBKD2AMVMJAVCNFSM6AAAAABRUS7MXGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMZSGY2DGNBXGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-13 11:31 UTC, CarstenHoffmannMarburg commented
> Sure, which relation would you advise me to use for Yeshaq and Matyas i. e. patrons / sponsors (ዘአጽሐፈ:)? śr., 13 lis 2024 o 11:51 Carsten Hoffmann ***@***.***> 

This is a good question. I think, we do not have a specific relation for sponsors or donors. You can either use saws:hasOwned (assuming, that the comissioning is some kind of ownership before it is presented to an instution or somebody else) or to explain it more explicitely in dc:relation and add a desc, e.g.:
`<relation name="dc:relation" active="PRS14590Matyas" passive="EMML1844"><desc>Commissioned <ref type="mss" corresp="EMML1844"/>.</desc></relation>`

Probably @eu-genia knows better.

2024-11-13 11:35 UTC, eu-genia commented
If these persons are referenced from the manuscript record with the relevant role it is not needed to insert such relations, as they are retrievable from attestations

2024-11-13 11:35 UTC, eu-genia approved these changes

2024-11-14 07:19 UTC, CarstenHoffmannMarburg approved these changes

2024-11-14 08:13 UTC, merged