Addisie esat zammana
BetaMasaheft/Persons pull request #986
Opened 2024-12-20 16:25 UTC by Addisie

2024-12-20 17:41 UTC, CarstenHoffmannMarburg requested changes

2024-12-20 17:41 UTC, CarstenHoffmannMarburg commented on new/PRS14593EsatZammana.xml
> +                  <persName xml:lang="gez" xml:id="n1">እሸት ዘመነ፡</persName>
Please use word divider after እሸት

2024-12-20 17:41 UTC, CarstenHoffmannMarburg commented on new/PRS14593EsatZammana.xml
> +                <title>Qasis ʾƎšat Zammana</title>
I think, it is not our common practice to include the title "qasis" in `<title>` here, but I do not know, if it is problematic and need to be deleted.

2024-12-21 11:59 UTC, eu-genia approved these changes

2024-12-21 13:10 UTC, CarstenHoffmannMarburg commented on new/PRS14593EsatZammana.xml
> +                <title> ʾƎšat Zammana</title>
Delete space before ʾƎšat.

2024-12-21 13:10 UTC, CarstenHoffmannMarburg approved these changes

2024-12-21 13:13 UTC, merged